name: ZUCC Auto Check1

on:
  schedule:
    - cron: '15 * * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Auto Check
        env:
          SCHOOL_ID: ${{ secrets.SCHOOL_ID }}
          PASSWORD: ${{ secrets.PASSWORD }}
          LOCATION: ${{ secrets.LOCATION }}
          AUTO_POSITION: ${{ secrets.AUTO_POSITION }}
          VACCINE: ${{ secrets.VACCINE }}
          SCKEY: ${{ secrets.SCKEY }}
        run: python main.py
      - name: Auto Check1
        env:
          SCHOOL_ID: ${{ secrets.SCHOOL_ID1 }}
          PASSWORD: ${{ secrets.PASSWORD1 }}
          LOCATION: ${{ secrets.LOCATION1 }}
          AUTO_POSITION: ${{ secrets.AUTO_POSITION1 }}
          VACCINE: ${{ secrets.VACCINE }}
          SCKEY: ${{ secrets.SCKEY }}
        run: python main.py
